language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: nuild
      script: yarn build
script:
  - npm test
  - npm run build
on :
  branch: master
deploy:
  provider: heroku
  api_key: $HEROK
  app: $HEROKU_APP